Feature/lists
VovanShaitan/ru-study-python pull request #1
Opened 2022-11-13 13:33 UTC by VovanShaitan

Implemented methods "replace" and "search". All tests OK.

2022-11-16 09:18 UTC, aleksandr-semenov-dbp requested changes

2022-11-16 09:18 UTC, aleksandr-semenov-dbp commented on exercises/lists.py
> +        max_elem = 0
Для данной задачи конечно прокатит, но вообще максимальный элемент обычно ищут не от 0, а от первого элемента. Предлагаю для понимания переименовать переменную во что-то типа `max_positive_elem`

2022-11-16 12:13 UTC, VovanShaitan commented on exercises/lists.py
> +        max_elem = 0
Сделал все-таки первый элемент. Будь в практике задание написать метод find_max_elem(input_list), он бы не прошел assert find_max_elem(input_list) == max(input_list).

2022-11-21 09:12 UTC, aleksandr-semenov-dbp approved these changes

2022-11-21 10:03 UTC, merged